POST http://localhost:8000/api/user/register
Content-Type: application/json

{
    "first_name": "Test",
    "last_name": "User",
    "email": "example@com.ua",
    "password": "Test123#",
    "phone": "+38000000000"
}

###
POST http://localhost:8000/api/user/sign-in
Content-Type: application/json

{
    "email": "example@com.ua",
    "password": "Test123#",
}

###
GET http://localhost:8000/user/companies
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8000/user/companies
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "title": "Test Name",
    "phone": "+38000000000",
    "description": "Some description"
}
